; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- CONFIGURACIÓN DE FLASH 4MB ---
board_upload.flash_size = 4MB
board_build.partitions = default.csv

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    bblanchon/ArduinoJson @ ^7.0.4

; --- LÍNEAS CLAVE PARA EL SUPER MINI Y TFT_eSPI ---
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DUSER_SETUP_LOADED=1
    -DGC9A01_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MISO=-1
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=9
    -DTFT_DC=8
    -DTFT_RST=7
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DSPI_FREQUENCY=27000000
    -DUSE_HSPI_PORT=1
    -DCORE_DEBUG_LEVEL=5